#!/bin/bash

yarn workspace @redhatinsights/backstage-plugin-kubernetes-info export-dynamic
cd plugins/kubernetes/
rm *.tgz
npm pack ./dist-dynamic
cd ../..
mv plugins/kubernetes/*.tgz .
sha256sum *.tgz | awk '{print $1}' | xxd -r -p | base64